handle provenance/who is undefined
WormBase/names pull request #150
Opened 2019-01-10 18:29 UTC by sibyl229

2019-01-11 10:03 UTC, mgrbyte requested changes
Yes, this is what  I was looking for.
Could you abstract apply a similar change (perhaps a fn?) to all the other provenance values pls (except provenance/why) ? (when, how, what)

2019-01-11 23:17 UTC, sibyl229 commented
@mgrbyte yeah, for sure. Please see if my newly pushed changes work for you.

2019-01-15 15:11 UTC, mgrbyte approved these changes

2019-01-15 15:11 UTC, merged

2019-01-15 15:11 UTC, mgrbyte commented
Thanks @sibyl229 :+1: