replace provenacne/why with why for forms and dialogs
WormBase/names pull request #263
Opened 2019-11-05 17:13 UTC by sibyl229

relates to #260

2019-11-07 12:00 UTC, mgrbyte requested changes

2019-11-07 12:00 UTC, mgrbyte commented on client/src/containers/Entity/EntityForm.js
> +    <NameField
Would it be possible to omit this change from this PR, the rest of the changes look great!
I'll create a separate ticket for the name optionality aspect.

2019-11-07 18:05 UTC, sibyl229 commented
Thanks @mgrbyte ! I moved that commit to a different PR.

2019-11-08 10:49 UTC, mgrbyte approved these changes

2019-11-08 16:37 UTC, merged